packages: []
catalogs:
  build:
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.1.2
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.2
    '@unocss/nuxt': ^66.5.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.2
    unocss: ^66.5.2
    unplugin: ^2.3.10
    vite: ^7.1.8
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@types/node': ^24.7.0
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.0

  frontend:
    '@vueuse/core': ^13.9.0
    pinia: ^3.0.3
    vue: ^3.5.22
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
