name: Crawl and Generate Recipe Data

on:
  schedule:
    - cron: '0 2 * * 1' # 每周一上午 10 点（北京时间）
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Run Crawl Script
        run: |
          python crawl.py

      - name: Commit and Push Generated Recipe Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'chore: auto update recipe data [ci skip]'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
